GRA-18, Create Table Service
scopra/centralized-reservation-system-backend pull request #3
Opened 2023-04-16 17:09 UTC by Tarik1700

Missing some tests, didn't have time, will add at a later time. Created many files, service controller and some endpoints for tables, also added functionality when restaurant gets created that tables get automatically created depending on the capacity of the restaurant. This still needs some refinment down the road, but for initial setup i believe it is enough.

2023-04-16 22:01 UTC, scopra requested changes
I'll take a more detailed look tomorrow regarding the controller and the infamous for loop logic, but overall it's great for a start

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/restaurant/controller/RestaurantController.java
> +        for (int i = 0; i < restaurant.getCapacity()/4; i++) {
Please try to find a different way to do this other than a for loop. Potentially, you can have a list of tables and stream through the list or something. I'll review the logic tomorrow, might have other comments. Also, the controller shouldn't do this stuff, you can delegate it to a helper class.

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/table/processor/TableProcessor.java
> +
You can maybe have the modified for loop logic here. Also, try to remove extra lines in files it looks more polished that way

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/entity/TableEntity.java
> +    @Override
I'm pretty sure you can have @ToString cover this, just make sure to exclude all objects that might cause infinite recursive calls, like RestaurantEntity, similar to my logic.

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/entity/TableEntity.java
> +    public boolean equals(Object o) {
Did you write this yourself or generate it with IntelliJ?

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/entity/TableEntity.java
> +    // Generate getters and setters for all the fields
Remove the comments if you don't need them

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/service/TableServiceImpl.java
> +public class TableServiceImpl implements TableService{
Make sure to CTRL ALT L and CTRL ALT O all of your code to format it

2023-04-16 22:01 UTC, scopra commented on src/test/java/com/ontime/crrs/cucumberglue/steps/RestaurantServiceSteps.java
> +    public void  thenRestaurantUpdated() {
😆

2023-04-16 22:01 UTC, scopra commented on src/test/java/com/ontime/crrs/cucumberglue/steps/TableRepositorySteps.java
> +        tableRepository.deleteAll();
We can eventually put all the repository cleanup methods we'll have in the general hooks file that will be called before all tests anyway, try that approach and see if it's convenient

2023-04-16 22:01 UTC, scopra commented on src/test/java/com/ontime/crrs/cucumberglue/steps/TableRepositorySteps.java
> +        tableRepository.deleteAll();
(If you have time now, if not then we'll see later)

2023-04-16 22:01 UTC, scopra commented on src/test/resources/features/TableService.feature
> +    Then the list of all tables is returned
Test logic is good, I'm probably not going to look at them in detail but test the problematic cases using your own judgment where we might get errors

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/restaurant/controller/RestaurantController.java
> +        for (int i = 0; i < restaurant.getCapacity()/4; i++) {
I still think we should reconsider this design with the fixed number of 4 per table together and have a good algorithm, it's very "skalamerija" right now

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/table/controller/TableController.java
> +public class TableController {
Did you test the controller btw?

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/table/controller/TableController.java
> +
So far, maybe add a delete table function. It's going to have some underlying logic related to subtracting capacity, but we'll figure it out together

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/table/controller/TableController.java
> +
The logic is for sure part of the processor you created.

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/business/table/exception/TableNotFoundException.java
> +public class TableNotFoundException  extends RuntimeException{
Straightforward, nothing to add

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/repository/TableRepository.java
> +
I can foresee a possible useful query to get table/id/whatever works by occupancy status, so we can filter (un)available tables if needed.

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/repository/TableRepository.java
> +
Also, whenever we change the capacity/4 solution, we are going to need a get table by capacity query

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/service/TableService.java
> +   List<TableEntity> findAllTables();
Come to think about it, when are we going to need this `findAllTables()` functionality? Maybe it would be more useful to define another custom query to get tables by restaurant name. You can find a nested property-type query in my repository, with _ in the name.

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/service/TableService.java
> +    boolean checkIfRestaurantExistsById(UUID id);
`checkIfTableExistsById`

2023-04-16 22:01 UTC, scopra commented on src/main/java/com/ontime/crrs/persistence/table/service/TableServiceImpl.java
> +public TableEntity updateTable(TableEntity table){
As far as I understood (and it makes sense to me), we are not going to have a functionality to modify tables. You can rename this to `addTable`, it's more descriptive of the purpose

2023-04-16 22:01 UTC, scopra commented on src/test/java/com/ontime/crrs/cucumberglue/steps/TableRepositorySteps.java
> +    public void thenShouldReturnListOfTables(int expectedSize) {
I'm pretty sure this shouldn't be defined here 😆

2023-04-16 22:01 UTC, scopra commented on src/test/resources/features/TableRepository.feature
> +  Perform CRUD operations with Table Entities
When you define custom queries, you can test them here, the other ones you don't have to

2023-04-16 22:01 UTC, scopra commented on src/test/resources/features/TableRepository.feature
> +  Perform CRUD operations with Table Entities
I'd like to have the custom queries tested at least (put off the service for later), because sometimes JPA is unpredictable

2023-04-24 17:45 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/persistence/table/entity/TableEntity.java
> +    public boolean equals(Object o) {
I believe it was generated by intelliJ

2023-04-24 17:48 UTC, Tarik1700 commented on src/test/java/com/ontime/crrs/cucumberglue/steps/TableRepositorySteps.java
> +        tableRepository.deleteAll();
Sadly 0 time currently. I believe we should postpone that

2023-04-24 17:49 UTC, Tarik1700 commented on src/test/resources/features/TableService.feature
> +    Then the list of all tables is returned
Currently it's kind of hard to test all the cases taking into consideration we don't have half of the BE done and connected, i think we should add them as we add endpoints, so we can see what the points of failure could be while actually using the endpoint and manually testing it

2023-04-24 17:50 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/business/table/controller/TableController.java
> +public class TableController {
Yup, works endpoints fire fine manually and when adding restaurant they are also being added as they should and everything is connected as well

2023-04-24 17:54 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/business/table/controller/TableController.java
> +
I'll add it in the controller, but without any special logic. I believe it's more important right now that we have the basic structure down, then we'll polish and add functions

2023-04-24 17:59 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/persistence/table/repository/TableRepository.java
> +
That's why i didn't create any over-engineered endpoints right now. The logic is constantly changing and not set at all. When we have the basics down we'll improve upon these basics

2023-04-24 18:00 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/persistence/table/service/TableService.java
> +   List<TableEntity> findAllTables();
I don't know how we would use it, but back then i was thinking that maybe we could use the findAllTables functionality for some calculations about the business rules, findalltables and check how many are taken at that time of day and act accordingly, something like that. It won't hurt us if it stays there.

2023-04-24 18:06 UTC, Tarik1700 commented on src/test/resources/features/TableRepository.feature
> +  Perform CRUD operations with Table Entities
I would like to postpone the testing for at least a big longer when we have the endpoints rock solid. I wouldn't want to create the tests now only to have to rework majority of them because our logic wasn't concrete at the time.

2023-04-24 18:07 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/business/restaurant/controller/RestaurantController.java
> +        for (int i = 0; i < restaurant.getCapacity()/4; i++) {
Taking into consideration our time, I don't really think we have the luxury of over-engineering these solutions right now. I would like to mark it as a low-priority feature right now, as we still need very basic things like login signup etc.

2023-04-24 18:09 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/business/table/processor/TableProcessor.java
> +
As i mentioned above, nothing is set in stone regarding this, i was making this as a very basic starting setup just so we have the DB table showing up, when we have FE connected with some endpoints and a working user, then we should slowly move forward to this while also integrating drools with all of this somehow.

2023-04-24 18:11 UTC, Tarik1700 commented on src/main/java/com/ontime/crrs/persistence/table/entity/TableEntity.java
> +    @Override
on second thought removing it cause it seems unnecessary now when i look at it.

2023-04-24 18:12 UTC, Tarik1700 commented
Fixed some of the comments

2023-04-26 20:09 UTC, scopra approved these changes

2023-04-29 11:57 UTC, KahrimanRr approved these changes

2023-04-29 12:04 UTC, merged